version: "3.9"

services:
  nginx:
    ports:
      - "8081:80"
  mysql:
    ports:
      - '3307:3306'

  adminer:
    image: adminer:latest
    container_name: "adminer"
    restart: always
    depends_on:
      - mysql
    networks:
      - local_network
    ports:
      - "8082:8080"
    environment:
      - ADMINER_DESIGN=nette
      - ADMINER_DEFAULT_SERVER=mysql


networks:
  main_proxy_ivdev_network:
    driver: bridge
  main_proxy_db_network:
    driver: bridge