version: "3.9"

services:
  nginx:
    ports:
      - "8081:80"
  mysql:
    ports:
      - '3307:3306'

networks:
  main_proxy_sandbox_network:
    driver: bridge
  main_proxy_db_network:
    driver: bridge